version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          command: |
            echo "START >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
            fastlane ios deploy
            echo "END   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
