platform :ios do
  before_all do
    if is_ci?
    end
  end

  lane :deploy do |options|
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'example.p12',
      certificate_password: ''
    )
  end
end
